### Getting all effects
GET http://localhost:3001/api/users

### Login
POST http://localhost:3001/api/login
Content-Type: application/json

{ "username":"testuser@gmail.com", "password":"ecotest111"}



### logout

DELETE http://localhost:3001/api/logout


### change personal data
PUT http://localhost:3001/api/users/update/1
Content-Type: application/json

{ "name":"Atabay","surname":"Surname","phone_number":"+393714920623"}
