### Getting all effects
GET http://localhost:3001/api/users

### Login
POST http://localhost:3001/api/login
Content-Type: application/json

{ "username":"testuser@gmail.com", "password":"ecotest111"}



### logout

DELETE http://localhost:3001/api/logout


### change personal data
PUT http://localhost:3001/api/users/update/1
Content-Type: application/json

{ "name":"Atabay","surname":"Surname","phone_number":"+393714920623"}



### signup

POST http://localhost:3001/api/signUp
Content-Type: application/json

{ "name":"Emin", "surname":"Suleymanov","phone_number":"+994505050505", "email":"emin@gmail.com", "hashed_password":"emin111"}


### Getting all effects

GET http://localhost:3001/api/airlines


### flight search

POST http://localhost:3001/api/searchFlights
Content-Type: application/json

{ "departure_date":"2023-05-09","arrival_airport":"MXP", "departure_airport":"KRK"}

### book flight

POST http://localhost:3001/api/bookFlight
Content-Type: application/json

{ "user_id":7,"flight_id":1295, "seat":"29B", "payment_status":"PAID", "checkin_status":"NOT","selected_class":"ECONOM", "paid_price":120, "baggage":[{"type":"Hand","kg":10,"amount":1},{"type":"Checkin","kg":20,"amount":1}]}


### Getting all flights of user

GET http://localhost:3001/api/bookedFlights/7


### Getting all seats of flight

GET http://localhost:3001/api/getSeatsOfFlight/2

### random flight create

POST http://localhost:3001/api/createflight
Content-Type: application/json

{     "departure_airport": 56,
      "arrival_airport": 69,
      "departure_date": "2023-05-11",
      "departure_time": "10:00:00",
      "arrival_date": "2023-05-11",
      "arrival_time": "12:10",
      "econom_price": 59.99,
      "business_price": 160,
      "first_class_price": 350,
      "airline": 4,
      "flight_number": "AB321"
}

### generate flights

POST http://localhost:3001/api/createFakeFlights/250
Content-Type: application/json
